// commands/motivation.js

const motivations = [
  "Dream big and dare to fail.",
  "Action is the foundational key to all success.",
  "Don't wait for opportunity. Create it.",
  "Your time is limited, don't waste it living someone else's life.",
  "Believe you can and you're halfway there.",
  "Small daily improvements over time lead to stunning results.",
  "It always seems impossible until it's done.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Focus on being productive instead of busy.",
  "Do what you can, with what you have, where you are.",
  "Everything you've ever wanted is on the other side of fear.",
  "Start where you are. Use what you have. Do what you can.",
  "The secret of getting ahead is getting started.",
  "You don't have to be great to start, but you have to start to be great.",
  "Doubt kills more dreams than failure ever will.",
  "The only way to do great work is to love what you do.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn't just find you. You have to go out and get it.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It’s going to be hard, but hard does not mean impossible.",
  "Don't stop when you're tired. Stop when you're done.",
  "Work hard in silence, let your success be your noise.",
  "Key to success is to focus on goals, not obstacles.",
  "Believe in yourself and all that you are.",
  "The best view comes after the hardest climb.",
  "Failure is the opportunity to begin again more intelligently.",
  "Don't count the days, make the days count.",
  "Turn your obstacles into opportunities.",
  "You are stronger than you think.",
  "Consistency is the key to real transformation.",
  "Hustle until your haters ask if you're hiring.",
  "Prove them wrong.",
  "Stay hungry, stay foolish.",
  "Your only limit is your mind.",
  "Be severe with yourself and soft with others.",
  "The expert in anything was once a beginner.",
  "Opportunities don't happen. You create them.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "A journey of a thousand miles begins with a single step.",
  "Your passion is waiting for your courage to catch up.",
  "Be so good they can't ignore you.",
  "Keep going. Everything you need will come to you at the perfect time.",
  "Doubt is a status quo. Don't accept it.",
  "Strive for progress, not perfection.",
  "You are capable of amazing things.",
  "Make each day your masterpiece.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Aim for the moon. If you miss, you may hit a star.",
  "Don't watch the clock; do what it does. Keep going.",
  "Keep your eyes on the stars, and your feet on the ground.",
  "You miss 100% of the shots you don't take.",
  "Act as if what you do makes a difference. It does.",
  "Quality is not an act, it is a habit.",
  "Light tomorrow with today.",
  "Never give up on a dream just because of the time it will take to accomplish it.",
  "It is never too late to be what you might have been.",
  "Limit your 'always' and your 'nevers'.",
  "Spread love everywhere you go.",
  "To live is the rarest thing in the world. Most people exist, that is all.",
  "Be yourself; everyone else is already taken.",
  "The mind is everything. What you think you become.",
  "An unexamined life is not worth living.",
  "Eighty percent of success is showing up.",
  "Your time is limited, so don't waste it.",
  "Winning isn't everything, but wanting to win is.",
  "There is no substitute for hard work.",
  "If you want to lift yourself up, lift up someone else.",
  "You can't cross the sea merely by standing and staring at the water.",
  "To succeed in life, you need two things: ignorance and confidence.",
  "God helps those who help themselves.",
  "If you tell the truth, you don't have to remember anything.",
  "The best revenge is massive success.",
  "The only person you are destined to become is the person you decide to be.",
  "Go confidently in the direction of your dreams.",
  "Discipline is choosing between what you want now and what you want most.",
  "If it doesn't challenge you, it won't change you.",
  "Never let your memories be greater than your dreams.",
  "Clear your mind of can't.",
  "Self-trust is the first secret of success.",
  "Every champion was once a contender that refused to give up.",
  "Fall seven times, stand up eight.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "You define your own life. Don't let other people write your script.",
  "You are never too old to set another goal or to dream a new dream.",
  "Happiness is not something readymade. It comes from your own actions.",
  "Be the change that you wish to see in the world.",
  "With the new day comes new strength and new thoughts.",
  "The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence.",
  "Optimize for action, not perfection.",
  "Energy flows where attention goes.",
  "You can do anything, but not everything.",
  "Done is better than perfect.",
  "Small efforts, repeated day in and day out.",
  "Growth and comfort do not coexist.",
  "Success is a series of small wins.",
  "The distance between dreams and reality is called action.",
  "Make your life a masterpiece; imagine no limitations on what you can be, have or do.",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears.",
  "There are no shortcuts to any place worth going.",
  "If you're going through hell, keep going.",
  "What you do today can improve all your tomorrows.",
  "You must do the things you think you cannot do.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Courage is resistance to fear, mastery of fear—not absence of fear.",
  "Stay focused and never give up.",
  "The key to living is giving.",
  "Don't compromise yourself. You are all you've got.",
  "Be proud of how hard you are trying.",
  "A little progress each day adds up to big results.",
  "Difficult roads often lead to beautiful destinations.",
  "Don't let yesterday take up too much of today.",
  "You learn more from failure than from success. Don't let it stop you.",
  "If you are working on something that you really care about, you don't have to be pushed.",
  "People who are crazy enough to think they can change the world, are the ones who do.",
  "Failure will never overtake me if my determination to succeed is strong enough.",
  "Knowing is not enough; we must apply. Wishing is not enough; we must do.",
  "We generate fears while we sit. We overcome them by action.",
  "Whether you think you can or think you can't, you're right.",
  "Security is mostly a superstition. Life is either a daring adventure or nothing.",
  "The man who has confidence in himself gains the confidence of others.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Creativity is intelligence having fun.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "Today's accomplishments were yesterday's impossibilities.",
  "The only place where success comes before work is in the dictionary.",
  "Too many of us are not living our dreams because we are living our fears.",
  "I find that the harder I work, the more luck I seem to have.",
  "All progress takes place outside the comfort zone.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don't be afraid to give up the good to go for the great.",
  "I owe my success to having listened respectfully to the very best advice, and then going away and doing the exact opposite.",
  "If you really look closely, most overnight successes took a long time.",
  "The real test is not whether you avoid this failure, because you won't. It's whether you let it harden or shame you into inaction.",
  "There is only one strategy for growth: hard work.",
  "Failure is another stepping stone to greatness.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "If you want to achieve greatness stop asking for permission.",
  "Things work out best for those who make the best of how things work out.",
  "To live a creative life, we must lose our fear of being wrong.",
  "If you are not willing to risk the usual you will have to settle for the ordinary.",
  "Trust because you are willing to accept the risk, not because it's safe or certain.",
  "Take up one idea. Make that one idea your life.",
  "All our dreams can come true, if we have the courage to pursue them.",
  "Good things come to people who wait, but better things come to those who go out and get them.",
  "If you do what you've always done, you'll get what you've always gotten.",
  "Success is walking through obstacles with unwavering intent.",
  "Just when the caterpillar thought the world was ending, he turned into a butterfly.",
  "Successful people do what unsuccessful people are not willing to do.",
  "Never strive to be a person of success, but rather a person of value.",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "If you don't value your time, neither will others.",
  "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.",
  "No one can make you feel inferior without your consent.",
  "The whole secret of a successful life is to find out what is one's destiny to do, and then do it.",
  "If you're going through a tough time, keep pushing forward.",
  "What seems to us as bitter trials are often blessings in disguise.",
  "The distance between insanity and genius is measured only by success.",
  "When you stop chasing the wrong things, you give the right things a chance to catch you.",
  "Don't count the obstacles, focus on the path.",
  "The starting point of all achievement is desire.",
  "Success is the sum of small efforts, repeated day-in and day-out.",
  "If you want to make a permanent change, stop focusing on the size of your problems and start focusing on the size of yourself.",
  "You may have to fight a battle more than once to win it.",
  "A goal is a dream with a deadline.",
  "In the middle of every difficulty lies opportunity.",
  "He who has a why to live can bear almost any how.",
  "You cannot change your destination overnight, but you can change your direction overnight.",
  "If you don't build your dream, someone else will hire you to help them build theirs.",
  "What you achieve by reaching your goals is not as important as what you become.",
  "Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice.",
  "To avoid criticism say nothing, do nothing, be nothing.",
  "Your talent determines what you can do. Your motivation determines how much you are willing to do.",
  "Build your own dreams, or someone else will hire you to build theirs.",
  "You can't use up creativity. The more you use, the more you have.",
  "Dream big, work hard, stay focused, and surround yourself with good people.",
  "Failure is the condiment that gives success its flavor.",
  "It's not whether you get knocked down, it's whether you get up.",
  "If you want to conquer fear, don't sit home and think about it. Go out and get busy.",
  "You must expect great things of yourself before you can do them.",
  "Either you run the day or the day runs you.",
  "The power of imagination makes us infinite.",
  "The best way to predict your future is to create it.",
  "You miss everything if you never take the first step.",
  "Success is getting what you want; happiness is wanting what you get.",
  "Do not let what you cannot do interfere with what you can do.",
  "There is no elevator to success. You have to take the stairs.",
  "Work hard, be kind, and amazing things will happen.",
  "Always do your best. What you plant now, you will harvest later.",
  "Change your thoughts and you change your world.",
  "Where there is a will, there is a way.",
  "Begin today, not tomorrow.",
  "Patience, persistence and perspiration make an unbeatable combination for success.",
  "Visualizing success is the first step to achieving it.",
  "Small steps in the right direction can turn out to be the biggest step of your life.",
  "Don't be afraid to stand for what you believe in, even if that means standing alone.",
  "Hard work beats talent when talent doesn't work hard.",
  "If you want something you've never had, you must be willing to do something you've never done.",
  "Be relentless in the pursuit of what sets your mind on fire.",
  "Stay foolish, stay ambitious.",
  "Doubt is a killer. You just have to know who you are and what you stand for.",
  "Believe in the power of your choices.",
  "No pressure, no diamonds.",
  "Silence is an answer too, but action speaks loudest.",
  "Daring to fail is daring to succeed.",
  "Make your passion your profession.",
  "Action conquers fear.",
  "Doubt vanishes when action begins.",
  "Turn pain into power.",
  "You don't need a new year to make a change, just a new day.",
  "Wake up with purpose.",
  "Strive for excellence, not perfection.",
  "A winner is a dreamer who never gives up.",
  "Focus on the solution, not the problem.",
  "Believe you deserve it and the world will serve it.",
  "Your speed doesn't matter, forward is forward.",
  "Everything you need is already inside you.",
  "Rise above the storm and you will find the sunshine.",
  "Your life is as good as your mindset.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "Your hard work will pay off.",
  "Never shrink yourself for extraordinary circumstances.",
  "Be a voice, not an echo.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Do it with passion or not at all.",
  "Don't tell people your plans. Show them your results.",
  "Keep climbing; the view from the top is worth it.",
  "When you feel like quitting, think about why you started.",
  "Stay true to your vision.",
  "Every moment is a fresh beginning.",
  "Mistakes are proof that you are trying.",
  "You are one decision away from a totally different life.",
  "Choose positivity today.",
  "Your potential is endless.",
  "Create the life you can't wait to wake up to.",
  "Small wins compound into huge victories.",
  "Work on yourself, for yourself.",
  "Turn obstacles into stepping stones.",
  "Keep pushing forward.",
  "Your mindset determines your reality.",
  "Every step counts, no matter how small.",
  "Focus on your growth, not your limits.",
  "You are stronger than your excuses.",
  "The secret to progress is getting started.",
  "Transform your thoughts and you transform your destiny.",
  "Don't wait for inspiration, create it.",
  "Make today count.",
  "Doubt yourself and you doubt your potential.",
  "Embrace the process.",
  "Small changes lead to big results.",
  "Your energy attracts your opportunity.",
  "Stay disciplined, stay focused.",
  "Success is a habit, not an accident.",
  "Never limit your vision.",
  "Rise and grind.",
  "Your ambition determines your success.",
  "Failure is a lesson, not a death sentence.",
  "Push past your comfort zone.",
  "Focus on what you can control.",
  "Consistency beats intensity every time.",
  "Believe in your journey.",
  "You hold the key to your own potential.",
  "Overcoming obstacles builds true character.",
  "Never let fear dictate your choices.",
  "Focus on the outcome, not the effort.",
  "Keep moving forward.",
  "Your determination defines your future.",
  "Be unstoppable.",
  "Work hard in quietness.",
  "Learn from yesterday, live for today, hope for tomorrow.",
  "Take the risk or lose the chance.",
  "Your passion is your power.",
  "Greatness requires sacrifice.",
  "Stay hungry for knowledge.",
  "You are the author of your own story.",
  "Turn dreams into actionable goals.",
  "Never give up on what truly matters.",
  "Focus on your strengths.",
  "Keep your eyes on the goal.",
  "Challenge yourself daily.",
  "Stay committed to your growth.",
  "Success demands daily effort.",
  "Believe in the power of persistence.",
  "Make every effort count.",
  "Push beyond limits.",
  "Your grit defines your success.",
  "Doubt fades with every step you take.",
  "Focus on progress, step by step.",
  "Consistency creates momentum.",
  "Your effort today shapes your tomorrow.",
  "Failure is feedback.",
  "Keep grinding until your vision is reality.",
  "Embrace every challenge as an opportunity.",
  "Your focus determines your reality.",
  "Stay persistent and patient.",
  "Action turns dreams into reality.",
  "Never compromise on your goals.",
  "Believe in the power of hard work.",
  "Small habits lead to massive results.",
  "Keep pushing, you are getting closer.",
  "Your dedication will yield results.",
  "Focus on long-term results over short-term comfort.",
  "Success is earned, not given.",
  "Stay true to your path.",
  "Your resilience is your greatest asset.",
  "Every day is a new chance to succeed.",
  "Work until your dreams become reality.",
  "Drive your own progress.",
  "Conquer your fears with action.",
  "Keep striving for greatness.",
];

async function motivationCommand(sock, chatId, message) {
  try {
    const quote = motivations[Math.floor(Math.random() * motivations.length)];
    
    await sock.sendMessage(chatId, { 
      text: `✨ *Motivation*\n\n${quote}` 
    }, { quoted: message });

  } catch (error) {
    console.error('Error in motivation command:', error);
    await sock.sendMessage(chatId, { 
      text: '❌ Failed to get motivation quote.' 
    }, { quoted: message });
  }
}

module.exports = motivationCommand;
